server:
  debug: false
  host: "0.0.0.0" # Current machine ip
  port: 5010
  drivers: 'drivers/chromedriver_mac'

database:
  host: "localhost"
  name: "naochallenge24"
  user: "postgres"
  password: "postgres"

nao:
  ip: "192.168.0.118"
  port: 9559
  user: "nao"
  password: "nao"